server:
  port: 8089

spring:
  application:
    name: order-service
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    #    driver-class-name: com.mysql.jdbc.Driver
    #    url: jdbc:mysql://localhost:3306/leyou1?useUnicode=true&characterEncoding=UTF-8
    #    username: root
    #    password: ""
    hikari:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/leyou1?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: ""
      maximum-pool-size: 50
      minimum-idle: 50
      auto-commit: true
  jpa:
    database: mysql
    show-sql: false
    open-in-view: false
    properties:
      hibernate.hbm2ddl.auto: update
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.format_sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.1.10
  swagger2:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳 #default 30
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期 #default 90
    prefer-ip-address: true
    ip-address: 127.0.0.1
    #instance-id: ${spring.application.name}:${server.port}

ribbon:
  ConnectTimeout: 1000 # 连接超时时间(ms)
  ReadTimeout: 4000 # 通信超时时间(ms)
  #OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 0 # 同一服务不同实例的重试次数
  MaxAutoRetries: 0 # 同一实例的重试次数

#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMillisecond: 10000 # 熔断超时时长:10000ms

leyou:
  jwt:
    pubKeyPath: /Users/davidzhang/Documents/dockerworkspace/rsa/rsa.pub # 公钥地址
    cookieName: LY_TOKEN
  worker:
    workedId: 1
    dataCenterId: 1

logging:
  level:
    com:
      zaxxer:
        hikari: debug

seata:
  enabled: true #开启配置
  application-id: seata-spring-boot-starter-samples  #客户端注册ID
  tx-service-group: default # 事务分组
  client:
    rm:
      lock:
        lock-retry-interval: 200
        lock-retry-times: 5
#        lock-retry-policy-branch-rollback-on-conflict: false





