server:
  port: 10010
  tomcat:
    max-threads: 400 # 最大工作线程数，默认200（4核8g内存，线程数800，一般是核数*200。操作系统做线程之间的切换调度是有系统开销的，所以不是越多越好。）
    min-spare-threads: 100 # 最小工作空闲线程数，默认10
    accept-count: 1000 # 等待队列长度，默认100

spring:
  application:
    name: api-gateway
  zipkin:
    # 不使用rabbitmq需要配置Zipkin服务器地址
    base-url: http://localhost:9411
  sleuth:
    sampler:
      # 配置采样比例，生产环境应调小，否则影响系统执行效率，或者改为rabbitMq方式
      # 一般用0.5
      probability: 1.0
#  redis:
#    enabled: false
  redis:
    #host: 192.168.1.10 #这个是配单机版
    enabled: true
    cluster:
      nodes: 192.168.1.10:6379, 192.168.1.10:6380, 192.168.1.10:6381, 192.168.1.10:6389, 192.168.1.10:6390, 192.168.1.10:6391
      max-redirects: 5
    jedis:
      pool:
        max-active: 10 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 5 # 连接池中的最大空闲连接
        max-wait: 1000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 5 # 连接池中的最小空闲连接
  redisson:
    enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
#    ip-address: 127.0.0.1
#    instance-id: ${spring.application.name}:${server.port}

#  关于Zuul的限流
#  用了origin在redis的key中会有ip地址（配了origin,url,user）
#   用：api-gateway:item-service:192.168.1.10:/goods/getOnSaleProduct:anonymous
#   不用： api-gateway:item-service:/goods/getOnSaleProduct:anonymous
#  用了user在redis的key中会有user name - 如anonymous (配了url,user)
#   用: api-gateway:item-service:/goods/getOnSaleProduct:anonymous
#   不用： api-gateway:item-service:/goods/getOnSaleProduct
zuul:
  ratelimit:
    enabled: true
    repository: REDIS
    default-policy-list: #全局限流
      - limit: 10 #optional - request number limit per refresh interval window
        refresh-interval: 60 #default value (in seconds) ＃60秒内超过 limit 次就限流
        type: #optional
          #- origin #origin是根据IP限流
          - url
#          - user
#    policy-list: #局部限流
#      order-service:
#        - limit: 5 #optional - request number limit per refresh interval window
#          #quota: 1000 #optional - request time limit per refresh interval window (in seconds)
#          refresh-interval: 60 #default value (in seconds)
#          type: #optional
#            - origin
#            - url
#            - user
  SendErrorFilter: # 对于自定义error filter，先要禁用Zuul默认的异常处理Filter
    error:
      disabled: true

  prefix: /api # 添加路由前缀 retryable: true
  add-host-header: true #携带请求本身的head信息
  sensitive-headers:  #敏感头过滤, 配置禁止使用的头信息，这里设置为null,否则set-cookie无效
  routes:
    item-service:
      path: /item-service/** # /*不匹配子路径（匹配/item-service/a /item-service/b）, /**不匹配子路径（匹配/item-service/a/a /item-service/b/b）
      #url: http://127.0.0.1:8081
      serviceId: item-service
    upload-service:
      path: /upload/**
      serviceId: upload-service #eureka中的微服务serviceId
      strip-prefix: false
    search-service:
      path: /search/**
      serviceId: search-service #eureka中的微服务serviceId
      strip-prefix: false
    page-service:
      path: /page/**
      serviceId: page-service #eureka中的微服务serviceId
      strip-prefix: false
    user-service:
      path: /user/**
      serviceId: user-service #eureka中的微服务serviceId
      strip-prefix: false
    auth-service:
      path: /auth/**
      serviceId: auth-service #eureka中的微服务serviceId
      strip-prefix: false
    cart-service:
      path: /cart/**
      serviceId: cart-service #eureka中的微服务serviceId
      strip-prefix: false
    order-service:
      path: /order/**
      serviceId: order-service #eureka中的微服务serviceId
      strip-prefix: false
    auth-oauth2-service:
      path: /uaa/**
      serviceId: auth-oauth2-service #eureka中的微服务serviceId
      strip-prefix: false
  host:
    max-total-connections: 2000 #http客户端连接池最大连接，默认是200， （ HttpClient 总连接数 ）
    max-per-route-connections: 500 #每个route可用的最大连接数，默认值是20 （ HttpClient 单个服务（即服务发现中的每个服务）连接数 ）
  semaphore:
    max-semaphores: 2000 #指的是1秒时间窗口内的事务/查询/请求, 默认值是100
  #以下2个配置解决了 - 解决Hystrix Dashboard显示中Thread pools一直处于Loading状态
  ribbon-isolation-strategy: thread #设置Hystrix隔离策略为线程池
  thread-pool:
    use-separate-thread-pools: true #每个路由使用独立的线程池


#zuul:
#  prefix: /api # 添加路由前缀 retryable: true
#  routes:
#    item-service: # 这里是路由id,随意写
#      path: /item/** # 这里是映射路径
##      serviceId: item-service # 指定服务名称
#      url: http://127.0.0.1:8081／ # 映射路径对应的实际url地址


ribbon:
  ConnectTimeout: 1000 # 连接超时时间(ms) # ribbon请求连接的超时时间，默认值2000
  ReadTimeout: 10000 # 通信超时时间(ms) # 负载均衡超时时间，默认值5000
  #OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 0 # 同一服务不同实例的重试次数 # 对切换实例的重试次数，默认1
  MaxAutoRetries: 0 # 同一实例的重试次数 # 对当前实例的重试次数，默认0

hystrix:
  threadpool:
    default:
      coreSize: 20
      maxQueueSize: 20
      queueSizeRejectionThreshold: 20 #Queue size rejection threshold is an artificial "max" size at which rejections will occur even if maxQueueSize has not been reached
  command:
    order-service:
      circuitBreaker:
        enabled: true
        requestVolumeThreshold: 10 #请求次数 默认20个, The default rolling window is 10 seconds
        sleepWindowInMilliseconds: 3000 #时间窗口期,that we will sleep before trying again after tripping the circuit
        errorThresholdPercentage: 60 #失败率达到多少后跳闸, must be >= 50%
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000 # 熔断超时时长:10000ms
          strategy:
            thread: THREAD

#            hystrix.threadpool.default.coreSize=100
#            hystrix.threadpool.default.maxQueueSize=1500
#            hystrix.threadpool.default.queueSizeRejectionThreshold=1000
#            hystrix.command.default.execution.timeout.enabled=false
#            hystrix.command.default.execution.isolation.strategy=THREAD

#暴露全部的监控信息
management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  hystrix:
    enabled: true

leyou:
  jwt:
    pubKeyPath: /Users/davidzhang/Documents/dockerworkspace/rsa/rsa.pub # 公钥地址
    cookieName: LY_TOKEN
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/login
      - /api/user/register
      - /api/user/code
      - /api/user/query
      - /api/user/registerForOAuth2
      - /api/item-service
      - /api/page
      - /api/uaa/oauth2/login





