server:
  port: 10010
spring:
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
#  instance:
#    prefer-ip-address: true
#    ip-address: 127.0.0.1
#    instance-id: ${spring.application.name}:${server.port}

zuul:
  prefix: /api # 添加路由前缀 retryable: true
  add-host-header: true #携带请求本身的head信息
  sensitive-headers:  #敏感头过滤, 配置禁止使用的头信息，这里设置为null,否则set-cookie无效
  routes:
    item-service:
      path: /item-service/**
      #url: http://127.0.0.1:8081
      serviceId: item-service
    upload-service:
      path: /upload/**
      serviceId: upload-service #eureka中的微服务serviceId
      strip-prefix: false
    search-service:
      path: /search/**
      serviceId: search-service #eureka中的微服务serviceId
      strip-prefix: false
    page-service:
      path: /page/**
      serviceId: page-service #eureka中的微服务serviceId
      strip-prefix: false
    user-service:
      path: /user/**
      serviceId: user-service #eureka中的微服务serviceId
      strip-prefix: false
    auth-service:
      path: /auth/**
      serviceId: auth-service #eureka中的微服务serviceId
      strip-prefix: false
    cart-service:
      path: /cart/**
      serviceId: cart-service #eureka中的微服务serviceId
      strip-prefix: false

#zuul:
#  prefix: /api # 添加路由前缀 retryable: true
#  routes:
#    item-service: # 这里是路由id,随意写
#      path: /item/** # 这里是映射路径
##      serviceId: item-service # 指定服务名称
#      url: http://127.0.0.1:8081／ # 映射路径对应的实际url地址


ribbon:
  ConnectTimeout: 250 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  #OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 0 # 同一服务不同实例的重试次数
  MaxAutoRetries: 0 # 同一实例的重试次数

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # 熔断超时时长:10000ms

leyou:
  jwt:
    pubKeyPath: /Users/davidzhang/Documents/dockerworkspace/rsa/rsa.pub # 公钥地址
    cookieName: LY_TOKEN
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/login
      - /api/user/register
      - /api/user/code
      - /api/user/query
      - /api/item-service
      - /api/page





