server:
  port: 10010
spring:
  application:
    name: api-gateway
  zipkin:
    # 不使用rabbitmq需要配置Zipkin服务器地址
    base-url: http://localhost:9411
  sleuth:
    sampler:
      # 配置采样比例，生产环境应调小，否则影响系统执行效率，或者改为rabbitMq方式
      # 一般用0.5
      probability: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
#    ip-address: 127.0.0.1
#    instance-id: ${spring.application.name}:${server.port}

zuul:
  prefix: /api # 添加路由前缀 retryable: true
  add-host-header: true #携带请求本身的head信息
  sensitive-headers:  #敏感头过滤, 配置禁止使用的头信息，这里设置为null,否则set-cookie无效
  routes:
    item-service:
      path: /item-service/**
      #url: http://127.0.0.1:8081
      serviceId: item-service
    upload-service:
      path: /upload/**
      serviceId: upload-service #eureka中的微服务serviceId
      strip-prefix: false
    search-service:
      path: /search/**
      serviceId: search-service #eureka中的微服务serviceId
      strip-prefix: false
    page-service:
      path: /page/**
      serviceId: page-service #eureka中的微服务serviceId
      strip-prefix: false
    user-service:
      path: /user/**
      serviceId: user-service #eureka中的微服务serviceId
      strip-prefix: false
    auth-service:
      path: /auth/**
      serviceId: auth-service #eureka中的微服务serviceId
      strip-prefix: false
    cart-service:
      path: /cart/**
      serviceId: cart-service #eureka中的微服务serviceId
      strip-prefix: false
    order-service:
      path: /order/**
      serviceId: order-service #eureka中的微服务serviceId
      strip-prefix: false
  host:
    max-total-connections: 2000 #http客户端连接池最大连接，默认是200， （ HttpClient 总连接数 ）
    max-per-route-connections: 500 #每个route可用的最大连接数，默认值是20 （ HttpClient 单个服务（即服务发现中的每个服务）连接数 ）
  semaphore:
    max-semaphores: 2000 #指的是1秒时间窗口内的事务/查询/请求, 默认值是100


#zuul:
#  prefix: /api # 添加路由前缀 retryable: true
#  routes:
#    item-service: # 这里是路由id,随意写
#      path: /item/** # 这里是映射路径
##      serviceId: item-service # 指定服务名称
#      url: http://127.0.0.1:8081／ # 映射路径对应的实际url地址


ribbon:
  ConnectTimeout: 1000 # 连接超时时间(ms) # ribbon请求连接的超时时间，默认值2000
  ReadTimeout: 10000 # 通信超时时间(ms) # 负载均衡超时时间，默认值5000
  #OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 0 # 同一服务不同实例的重试次数 # 对切换实例的重试次数，默认1
  MaxAutoRetries: 0 # 同一实例的重试次数 # 对当前实例的重试次数，默认0

hystrix:
  threadpool:
    default:
      coreSize: 100
      maxQueueSize: 1500
      queueSizeRejectionThreshold: 1000
  command:
    default:
      execution:
        isolation:
          strategy:
            thread: THREAD
            timeoutInMillisecond: 10000 # 熔断超时时长:10000ms

#            hystrix.threadpool.default.coreSize=100
#            hystrix.threadpool.default.maxQueueSize=1500
#            hystrix.threadpool.default.queueSizeRejectionThreshold=1000
#            hystrix.command.default.execution.timeout.enabled=false
#            hystrix.command.default.execution.isolation.strategy=THREAD

leyou:
  jwt:
    pubKeyPath: /Users/davidzhang/Documents/dockerworkspace/rsa/rsa.pub # 公钥地址
    cookieName: LY_TOKEN
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/login
      - /api/user/register
      - /api/user/code
      - /api/user/query
      - /api/item-service
      - /api/page





