server:
  port: 8093
  servlet:
    context-path: /uaa

spring:
  application:
    name: auth-oauth2-service
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    #    driver-class-name: com.mysql.jdbc.Driver
    #    url: jdbc:mysql://localhost:3306/leyou1?useUnicode=true&characterEncoding=UTF-8
    #    username: root
    #    password: ""
    hikari:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/leyou1?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: ""
      maximum-pool-size: 5
      minimum-idle: 5
      auto-commit: true
  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate.hbm2ddl.auto: update
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.format_sql: true
  redis:
    enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1

leyou:
  jwt:
    secret: leyou@Login(Auth}*^31)&heiMa% # 登录校验的密钥
    pubKeyPath: /Users/davidzhang/Documents/dockerworkspace/rsa/rsa.pub # 公钥地址
    priKeyPath: /Users/davidzhang/Documents/dockerworkspace/rsa/rsa.pri # 私钥地址
    expire: 60 # 过期时间,单位分钟
    cookieName: LY_TOKEN
  auth:
    clientId: c1
    clientSecret: secret
    grantType: password
