server:
  port: 8092 #8091 is for seata-server, so we can not use it here
  tomcat:
    max-threads: 400 # 最大工作线程数，默认200（4核8g内存，线程数800，一般是核数*200。操作系统做线程之间的切换调度是有系统开销的，所以不是越多越好。）
    min-spare-threads: 100 # 最小工作空闲线程数，默认10
    accept-count: 1000 # 等待队列长度，默认100

spring:
  application:
    name: onsale-service
  zipkin:
    # 不使用rabbitmq需要配置Zipkin服务器地址
    base-url: http://localhost:9411
  sleuth:
    sampler:
      # 配置采样比例，生产环境应调小，否则影响系统执行效率，或者改为rabbitMq方式
      # 一般用0.5
      probability: 1.0
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    #    driver-class-name: com.mysql.jdbc.Driver
    #    url: jdbc:mysql://localhost:3306/leyou1?useUnicode=true&characterEncoding=UTF-8
    #    username: root
    #    password: ""
    hikari:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/leyou1?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: ""
      maximum-pool-size: 50
      minimum-idle: 30
      auto-commit: true
  jpa:
    database: mysql
    show-sql: false
    open-in-view: false
    properties:
      hibernate.hbm2ddl.auto: update
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.format_sql: true
      hibernate.generate_statistics: false
  rabbitmq:
    host: 192.168.1.2
    username: leyou
    password: leyou
    virtual-host: /leyou
    listener:
      simple:
        acknowledge-mode: manual
#        prefetch: 1
#        retry:
#          enabled: true
#          max-attempts: 3
    template:
      mandatory: true #是否启用强制信息；默认false ＃要触发returnedMessage回调函数，我们必须设置mandatory=true
#      retry:
#        enabled: true
#        initial-interval: 10000ms
#        max-interval: 30000ms
#        multiplier: 2
#      exchange: leyou.item.exchange
    publisher-confirms: true
    publisher-returns: true


  jackson:
    default-property-inclusion: non_null
  redis:
    #host: 192.168.1.2 #这个是配单机版
    enabled: true
    cluster:
      nodes: 192.168.1.2:6379, 192.168.1.2:6380, 192.168.1.2:6381, 192.168.1.2:6389, 192.168.1.2:6390, 192.168.1.2:6391
      max-redirects: 5
    jedis:
      pool:
        max-active: 30 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        max-wait: 1000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 10 # 连接池中的最小空闲连接
  swagger2:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳 #default 30
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期 #default 90
    prefer-ip-address: true
    ip-address: 127.0.0.1
    #instance-id: ${spring.application.name}:${server.port}

ribbon:
  ConnectTimeout: 1000 # 连接超时时间(ms)
  ReadTimeout: 4000 # 通信超时时间(ms)
  #OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 0 # 同一服务不同实例的重试次数
  MaxAutoRetries: 0 # 同一实例的重试次数

feign:
  hystrix:
    enabled: true

hystrix:
  threadpool:
    default:
      coreSize: 100 # core size of thread pool
      maximumSize: 200 # maximum size of thread pool, it only gets applied if allowMaximumSizeToDivergeFromCoreSize is true
      allowMaximumSizeToDivergeFromCoreSize: true
      maxQueueSize: 200
      queueSizeRejectionThreshold: 200
  command:
    GoodsClient#decreaseStock(List):
      isolation:
        thread:
          timeoutInMilliseconds: 1000 # 熔断超时时长:10000ms
        strategy:
          thread: THREAD
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000 # 熔断超时时长:10000ms
          strategy:
            thread: THREAD

#暴露全部的监控信息
management:
  endpoints:
    web:
      exposure:
        include: "*"

threadpool:
  onsale:
    corePoolSize: 10 #CPU密集型(没有阻塞，CPU一直全速运行), 一般公式：CPU核+1个线程的线程池
    maximumPoolSize: 10
    queueCapacity: 10000 #预计并发
    keepAliveSeconds: 1
    enabled: true


leyou:
  jwt:
    pubKeyPath: /Users/davidzhang/Documents/dockerworkspace/rsa/rsa.pub # 公钥地址
    cookieName: LY_TOKEN
  worker:
    workedId: 1
    dataCenterId: 1
  waitinglist:
    exchange: leyou.waitinglist.exchange
    queue: leyou.waitinglist.queue
    routingKey: leyou.waitinglist.routingkey
    exchangeType: direct


logging:
  level:
    root: warn
    com:
      zaxxer:
        hikari: warn
    io:
      seata: error

seata:
  enabled: true #开启配置
  application-id: seata-spring-boot-starter-samples  #客户端注册ID
  tx-service-group: default # 事务分组
#  client:
#    rm:
#      lock:
#        lock-retry-interval: 200
#        lock-retry-times: 5
#        lock-retry-policy-branch-rollback-on-conflict: false





