server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/leyou1?useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: ""
    hikari:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/leyou1?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: ""
      maximum-pool-size: 5
      minimum-idle: 5
      auto-commit: true
  jpa:
    database: mysql
    show-sql: true
    open-in-view: false
    properties:
      hibernate.hbm2ddl.auto: update
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.format_sql: true
  rabbitmq:
    host: 192.168.1.11
    username: leyou
    password: leyou
    virtual-host: /leyou
    listener:
      simple:
        prefetch: 1
        retry:
          enabled: true
          max-attempts: 3
    template:
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 30000ms
        multiplier: 2
      exchange: leyou.item.exchange
    publisher-confirms: true
    publisher-returns: true

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳 #default 30
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期 #default 90
    prefer-ip-address: true
    ip-address: 127.0.0.1
    #instance-id: ${spring.application.name}:${server.port}

#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          strategy: Semaphore


leyou:
  transaction:
    exchange: leyou.transaction.exchange
    queue: leyou.transaction.queue
    routingKey: leyou.transaction.routingKey
    exchangeType: direct

logging:
  level:
    com:
      zaxxer:
        hikari: info