server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leyou1
    username: root
    password: ""
#    hikari:
#      maximum-pool-size: 30
#      minimum-idle: 10
  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate.hbm2ddl.auto: update
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳 #default 30
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期 #default 90
    prefer-ip-address: true
    ip-address: 127.0.0.1
    #instance-id: ${spring.application.name}:${server.port}