server:
  port: 8081
  tomcat:
    max-threads: 400 # 最大工作线程数，默认200（4核8g内存，线程数800，一般是核数*200。操作系统做线程之间的切换调度是有系统开销的，所以不是越多越好。）
    min-spare-threads: 100 # 最小工作空闲线程数，默认10
    accept-count: 1000 # 等待队列长度，默认100


spring:
  application:
    name: item-service
  zipkin:
    # 不使用rabbitmq需要配置Zipkin服务器地址
    base-url: http://localhost:9411
  sleuth:
    sampler:
      # 配置采样比例，生产环境应调小，否则影响系统执行效率，或者改为rabbitMq方式
      # 一般用0.5
      probability: 1.0
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/leyou1?useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: ""
    hikari:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/leyou1?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: ""
      maximum-pool-size: 50
      minimum-idle: 30
      auto-commit: true
  jpa:
    database: mysql
    show-sql: true
    open-in-view: false
    properties:
      hibernate.hbm2ddl.auto: update
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.format_sql: true
      hibernate.generate_statistics: false
  rabbitmq:
    host: 192.168.1.2
    username: leyou
    password: leyou
    virtual-host: /leyou
    listener:
      simple:
        prefetch: 1
        retry:
          enabled: true
          max-attempts: 3
    template:
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 30000ms
        multiplier: 2
      exchange: leyou.item.exchange
    publisher-confirms: true
    publisher-returns: true
  redis:
    #host: 192.168.1.2 #这个是配单机版
    enabled: true
    cluster:
      nodes: 192.168.1.2:6379, 192.168.1.2:6380, 192.168.1.2:6381, 192.168.1.2:6389, 192.168.1.2:6390, 192.168.1.2:6391
      max-redirects: 5
    jedis:
      pool:
        max-active: 10 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 5 # 连接池中的最大空闲连接
        max-wait: 1000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 5 # 连接池中的最小空闲连接
  redisson:
    enabled: true
    cluster: true

    #nodes: 192.168.1.2:6379 #这个是配单机版
    nodes: 192.168.1.2:6379, 192.168.1.2:6380, 192.168.1.2:6381, 192.168.1.2:6389, 192.168.1.2:6390, 192.168.1.2:6391 #这个是配集群版

    #password: xxxx

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳 #default 30
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期 #default 90
    prefer-ip-address: true
    ip-address: 127.0.0.1
    #instance-id: ${spring.application.name}:${server.port}

#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          strategy: Semaphore


leyou:
  transaction:
    exchange: leyou.transaction.exchange
    queue: leyou.transaction.queue
    routingKey: leyou.transaction.routingKey
    exchangeType: direct

logging:
  level:
    root: warn
    com:
      zaxxer:
        hikari: warn

seata:
  enabled: true #开启配置
  application-id: seata-spring-boot-starter-samples  #客户端注册ID
  tx-service-group: default # 事务分组
#  client:
#    rm:
#      lock:
#        lock-retry-interval: 200
#        lock-retry-times: 5
#        lock-retry-policy-branch-rollback-on-conflict: false



